import type { Metadata } from "next";
import "../src/assets/css/globals.css";
import { geistSans, geistMono } from "@/fonts/fonts";
import { Suspense } from "react";
import Loading from "./loading";



export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
